name: remita_flutter_sdk
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  crypto: ^3.0.1
  encrypt: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

